all:
	#g++ -std=gnu++14 -Wall -Wextra -Werror --pedantic -O2 calculator00.cpp -o calculator.out
	g++ -std=gnu++14 -Wall -Wextra -Werror --pedantic -O2 calculator01.cpp -o calculator.out
clean:
	rm -rf *.o calculator.out
