all:
	g++ -std=gnu++14 -Wall -Wextra --pedantic -O2 calculator09.cpp -o calculator.out
	#g++ -std=gnu++14 -Wall -Wextra -Werror --pedantic -O2 calculator09.cpp -o calculator.out
clean:
	rm -rf *.o calculator.out
