all:
#	g++ -std=gnu++14 -Wall -Wextra -Werror --pedantic -O2 calculator08buggy.cpp -o calculator08buggy.out
	g++ -std=gnu++14 -Wall -Wextra --pedantic -O2 calculator08buggy.cpp -o calculator08buggy.out
clean:
	rm -rf *.o calculator08buggy.out
